### ISSUE TITLE
Error while processing v8.log - TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by PraveenRamakrishna** [mapbox/flamebearer#12]
While processing attached v8 log, following error is thrown.

internal/fs/utils.js:537
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (fs.js:424:10)
    at ReadStream.open (internal/fs/streams.js:146:13)
    at new ReadStream (internal/fs/streams.js:134:10)
    at Object.createReadStream (fs.js:1888:10)
    at Object.<anonymous> (C:\Users\I537607\scoop\persist\nvm\nodejs\v12.18.0\node_modules\flamebearer\bin\flamebearer:10:40)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_INVALID_ARG_TYPE'
[isolate-0000019DFAB4A890-2000-v8.zip](https://github.com/mapbox/flamebearer/files/4931269/isolate-0000019DFAB4A890-2000-v8.zip)

Could you please help me here.

**Comment by fmileto** [comment]
Same issue there

**Comment by chenrui333** [comment]
works for me. 

```
node --prof app.js
node --prof-process --preprocess -j isolate*.log | flamebearer
```

I have tested with both nodev14 and nodev16
